### N.B: the passwords here must be the database passwords
development:
  user: fedoraAdmin
  password:
  url: http://127.0.0.1:8080/fedora
test: &TEST
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8080fedora
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8080/fedora
cucumber:
  <<: *TEST