development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8080/fedora
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  url:  <%= "http://127.0.0.1:8080}/fedora" %>
  #url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT']}/fedora-test" %>
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8080/fedora
cucumber:
  <<: *TEST
